[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npm run build"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
